### ISSUE TITLE
Typeclasses, etc.

### ISSUE THREAD

**Issue by tomjaguarpaw** [schell/renderable#1]
Futher to our exchange on HN (https://news.ycombinator.com/item?id=11140698):

I wouldn't say your usage of a typeclass from `Primitive` is _unidiomatic_.  In fact plenty of Haskellers like writing that way.  I happen to not, so I'll suggest another way and you can consider whether you think it's suitable for your use case.

Instead of a class I would have a datatype

```
data Primitive m t r a =
    { canAllocPrimitive :: r -> a -> Bool
    , compilePrimitive :: r -> a -> m (Renderer m t)
    }
```

and define a value of that for each type you want to be "primitive".  You can even make a type primitive in two ways (unlike with a typeclass).

Then you would have

```
getRenderer :: (Hashable a, Monad m)
            => Primitive m t r a
            -> Cache m t
            -> a
            -> m (Cache m t)
```

and so on for the other functions which are currently `Primitive` polymorphic.

I'd then probably go one step further and replace `Primitive` with `r -> a -> Primitive' m t` where

```
data Primitive' m t =
    { canAllocPrimitive' :: Bool
    , compilePrimitive' :: m (Renderer m t)
    }
```

Further simplifications may be possible, but I'd need to know more about your domain.

Hope that's interesting.

**Comment by schell** [comment]
Ah yes - I knew almost any type class can be replaced with a record, but I can't remember why I thought I couldn't do this here. I've actually been meaning to try this on this library. I recently did the same to another lib of mine. Thanks for the insight.
